# Generated by Django 2.0.13 on 2019-02-22 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Patient', models.CharField(max_length=200)),
                ('FieldOne', models.TextField()),
                ('FieldTwo', models.TextField()),
                ('FieldThree', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Date_of_Uploading', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name_of_FileUploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
