# Generated by Django 2.0.13 on 2019-02-22 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedRecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Patient', models.CharField(max_length=200)),
                ('FieldOne', models.TextField()),
                ('FieldTwo', models.TextField()),
                ('Date_of_Prescription', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_of_Uploading', models.DateTimeField(blank=True, null=True)),
                ('Name_of_FileUploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='records',
            name='Name_of_FileUploader',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
